### ISSUE TITLE
reduceBy to visit multiple files and / or ranges?

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/GenomicFileViews#2]
Created the `reduceBy` branch with an iteration on the `delegateBy` idea. Roughly,

    reduceByRange(X, MAP, REDUCE, ..., ITERATE=FALSE)
    reduceByFile(X, MAP, REDUCE, ..., ITERATE=FALSE)

goes in one direction or other other across X. MAP is a function taking arguments FILE, RANGE. It is invoked for each combination of file / range in X. REDUCE is a function that either receives a list X of results of MAP invocations (e.g., of a single range, across files), or X and Y like in base::Reduce. There's some basic illustrations in inst/script/reduceBy_ideas.R; performance benefits alot from BiocParallel v. 0.5.6.

Probably BiocParallel needs to implement bpReduce as something re-usable.

Thoughts?

**Comment by vobencha** [comment]
Closed.
